server:
    port: 10189
    servlet:
        context-path: /
    session:
        cookie:
          name: OAUTH2SESSION
datasource:
    url: jdbc:mysql://192.168.1.167:3306/db_newactivity?characterEncoding=utf8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
jpaproperties:
    show_sql: true
    format_sql: true
    autoReconnect:  true
    hbm2ddl_auto: update
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    entitypackages: org.baseframework.activity.models
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: wx046f2c7810964e1a
      clientSecret: 123456
      accessTokenUri: http://open.ngork.guomer.cn/oauth/token
      userAuthorizationUri: http://open.ngork.guomer.cn/oauth/authorize
    resource:
      userInfoUri: http://open.ngork.guomer.cn/api/user
spring:
  freemarker:
    request-context-attribute: request  #req访问request
    suffix: .html  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点
wechat: #微信多个公众号配置
  configs:
    - appId:
      secret:
      token:
      aesKey:

logging:
   file: ./logs/app.log
community:
   multi:
     authentication-pattern: /activity/{appKey}/**
        