server:
    port: 10189
    servlet:
        context-path: /ActivityManager
    session:
        cookie:
          name: OAUTH2SESSION
datasource:
    url: jdbc:mysql://localhost:3306/db_activity?characterEncoding=utf8
    username: root
    password: 
    driverClassName: com.mysql.jdbc.Driver
jpaproperties:
    show_sql: true
    format_sql: true
    autoReconnect:  true
    hbm2ddl_auto: update
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    entitypackages: org.baseframework.activity.models
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: bd1c0a783ccdd1c9b9e4
      clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
      accessTokenUri: http://192.168.1.48:10184/oatuhserver/oauth/token
      userAuthorizationUri: http://192.168.1.48:10184/oatuhserver/oauth/authorize
    resource:
      userInfoUri: http://192.168.1.48:10184/oatuhserver/user/me
spring:
  freemarker:
    request-context-attribute: request  #req访问request
    suffix: .html  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点
    
        